language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      name: "Rust: nightly"

    - rust: 1.31.0

    - rust: stable
      name: clippy
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy

    - rust: nightly
      name: wasm32
      before_script:
        - rustup target add wasm32-unknown-unknown
      script:
        - cargo build --target=wasm32-unknown-unknown -p cqrs-core -p cqrs -p cqrs-todo-core

    - rust: nightly
      name: rustfmt
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

  allow_failures:
    - rust: nightly
      name: "Rust: nightly"

install:
  - rustc -vV
  - cargo -vV

  # Install kcov.
  - mkdir -p ~/.cargo/bin
  - sh src/install_kcov.sh
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
  - export RUSTFLAGS="-C link-dead-code"
  - kcov --version

script:
  - cargo build
  - cargo test

  - if [ $TRAVIS_OS_NAME = linux ]; then cargo run -- kcov --verbose --no-clean-rebuild --lib --coveralls; fi