condense_wildcard_suffixes = true
merge_imports = true
match_block_trailing_comma = true
reorder_impl_items = true
# report_todo = "Always"
report_fixme = "Always"
use_field_init_shorthand = true
use_try_shorthand = true
unstable_features = true
