[package]
name = "cqrs"
version = "0.1.0-alpha.0"
authors = ["Marcus Griep <marcus@griep.us>"]
description = "An event-sourced command-query system"
license = "Apache-2.0"
readme = "../README.md"
documentation = "https://docs.rs/cqrs"
repository = "https://github.com/cq-rs/cqrs"
edition = "2018"

[dependencies]
cqrs-core = { version = "0.1.0-alpha.0", path = "../cqrs-core" }
hashbrown = "0.1"
parking_lot = "0.7"
void = "1.0"

[dev-dependencies]
static_assertions = "0.3"
cqrs-todo-core = { version = "0.1.0-alpha.0", path = "../cqrs-todo-core" }

[badges]
travis-ci = { repository = "cq-rs/cqrs", branch = "master" }